[tiles]
object108_name=text_gravity
object039_image=text_sleep
object115_tiling=-1
object115_colour=4,2
object108_image=text_gravity
object115_root=0
object115_image=cat
object049_name=text_cute
object076_name=text_turn
object076_image=text_turn
object039_name=text_sleep
changed=object076,object049,object115,object039,object054,object068,object108,object048,

[general]
name=first level
selectorX=-1
paletteroot=1
paths=0
customparent=1level
palette=default.png
levels=0
specials=0
leveltype=0
unlockcount=0
selectorY=-1

