[tiles]
object115_colour=4,2
object115_tiling=-1
object076_name=text_turn
object076_image=text_turn
object039_image=text_sleep
object108_name=text_gravity
object115_root=0
object108_image=text_gravity
object019_name=text_lenlo
object115_image=cat
object031_name=lenlo
object031_image=error
object049_name=text_cute
object039_name=text_sleep
changed=object049,object031,object019,object068,object108,object076,object039,object054,object048,object115,

[general]
selectorY=-1
unlockcount=0
leveltype=0
specials=0
levels=0
palette=default.png
customparent=1level
paths=0
paletteroot=1
selectorX=-1
name=first level

