[tiles]
object114_name=text_cat
object114_colour=4,1
object115_image=cat
object114_root=0
object115_tiling=-1
object114_image=text_cat
object115_root=0
object114_activecolour=4,2
object115_colour=4,2
object115_name=cat
changed=object115,object114,

[general]
selectorY=-1
unlockcount=0
selectorX=-1
leveltype=0
specials=0
paths=0
levels=0
palette=default.png
customparent=2level
paletteroot=1
name=first level

