[tiles]
object114_colour=4,1
object114_name=text_cat
object114_activecolour=4,2
object115_colour=4,2
object115_image=cat
object114_image=text_cat
object115_root=0
object114_root=0
object115_tiling=-1
object115_name=cat
changed=object115,object114,

[general]
name=first level
paletteroot=1
customparent=2level
palette=default.png
levels=0
paths=0
specials=0
leveltype=0
selectorX=-1
unlockcount=0
selectorY=-1

